- k8s-inference/README.md
- k8s-training/README.md
Added more detail on how to connect to the cluster.
> Cluster connection

- soperator/.gitignore
- soperator/README.md
- soperator/installations/example/.envrc
- Minor quality-of-life improvements
- Fix check that `.aws_secret_access_key` contains non-whitespace characters
> [Soperator] Update `README` and `.envrc`

- soperator/installations/example/.envrc
- soperator/test/mlperf-gpt3/gpt3-impl-4.0-nvidia/config_H100x8_NODEx64_TPx4_PPx8_VPx4_MINBSx128_MICBSx2.sh
- soperator/test/mlperf-gpt3/gpt3-impl-4.0-nvidia/config_H100x8_NODEx8_TPx8_PPx8_VPx4_MINBSx1536_MICBSx1.sh
- soperator/test/mlperf-gpt3/gpt3-impl-4.0-nvidia/config_H200x8_NODEx64_TPx2_PPx8_VPx4_MINBSx128_MICBSx2.sh
- soperator/test/mlperf-gpt3/gpt3-impl-4.0-nvidia/config_H200x8_NODEx8_TPx4_PPx8_VPx4_MINBSx128_MICBSx2.sh
- soperator/test/mlperf-gpt3/gpt3-impl-4.0-nvidia/config_H200x8_NODEx8_TPx8_PPx8_VPx4_MINBSx3072_MICBSx1.sh
- soperator/test/mlperf-gpt3/gpt3-impl-4.0-nvidia/start.sh
- [FIX] Removed leftovers with storing AWS secret access key in local file
- [FIX] Fixed incorrect echoing in GPT3 runner
- [ENH] Added an option to set job timeout with GPT3 runner
> Bash script enhancements

- k8s-inference/README.md
- k8s-training/README.md
Fixed links in the observability section for k8s-inference and k8s-training
> Fix readme loki sa accesskey

- compute-testing/provider.tf
- k8s-inference/provider.tf
- k8s-training/provider.tf
- modules/gluster-module/versions.tf
- modules/gpu-operator/versions.tf
- modules/kuberay/versions.tf
- modules/network-operator/versions.tf
- modules/nfs-server/provider.tf
- modules/o11y/versions.tf
- nfs-server/provider.tf
- slurm/versions.tf
- soperator/installations/example/terraform.tf
- soperator/modules/filestore/terraform.tf
- soperator/modules/k8s/terraform.tf
- wireguard/provider.tf
Change terraform provider source to the new S3 location - 
terraform-provider.storage.eu-north1.nebius.cloud/nebius/nebius
> Change terraform provider source

- soperator/installations/example/main.tf
- soperator/modules/available_resources/main.tf
+ Take less ephemeral storage for reserve
> Precise calculation of allocatable CPU & RAM [MSP-4006]

- k8s-inference/terraform.tfvars
Add a placeholder variable for the tenant_id to terraform.tfvars, as it's required for deploying this solution.
> ➕ Add tenant_id variable placeholder to terraform.tfvars

- soperator/installations/.gitignore
- soperator/installations/example/main.tf
- soperator/installations/example/terraform.tfvars
- soperator/installations/example/variables.tf
- soperator/modules/backups/main.tf
- soperator/modules/backups/templates/k8up_operator_values.yaml.tftpl
- soperator/modules/backups/templates/k8up_schedule.yaml.tftpl
- soperator/modules/backups/variables.tf
- soperator/modules/monitoring/outputs.tf
- soperator/modules/slurm/main.tf
- soperator/modules/slurm/outputs.tf
> Jail backup fixes

- wireguard/environment.sh
- wireguard/locals.tf
- wireguard/terraform.tfvars
This PR will need to be coordinated with an update to the public docs site to update the WireGuard tutorial.
> wireguard: store terraform state in object storage

- skypilot/README.md
- skypilot/examples/ai-training.yaml
- skypilot/examples/basic-job.yaml
- skypilot/examples/test-cloud-bucket.yaml
- skypilot/nebius-setup.sh
We can use mount Nebius Object Store buckets to the filesystem. 
https://docs.skypilot.co/en/latest/reference/storage.html
> SkyPilot object store support

- soperator/modules/slurm/main.tf
- soperator/modules/slurm/templates/helm_values/slurm_cluster.yaml.tftpl
- soperator/modules/slurm/variables.tf
Added SConfigController values to the helm template
Making changes with the main PR into soperator: https://github.com/nebius/soperator/pull/543
> 508: Added values for sconfigcontroller helm

- soperator/installations/example/main.tf
- soperator/installations/example/terraform.tfvars
- soperator/installations/example/variables.tf
- soperator/modules/slurm/main.tf
- soperator/modules/slurm/templates/helm_values/slurm_cluster.yaml.tftpl
- soperator/modules/slurm/variables.tf
Supported in soperator here: https://github.com/nebius/soperator/pull/673
> Add customization for slurm healthchecks to terraform

- skypilot/nebius-setup.sh
Added `--parent-id "$NEBIUS_PROJECT_ID"` flag to some commands in `skypilot/nebius-setup.sh`
> add `--parent-id "$NEBIUS_PROJECT_ID"` flag to `nebius-setup.sh`

- soperator/installations/example/main.tf
- soperator/installations/example/terraform.tfvars
- soperator/installations/example/variables.tf
- soperator/modules/slurm/main.tf
- soperator/modules/slurm/templates/helm_values/terraform_fluxcd_values.yaml.tftpl
- soperator/modules/slurm/variables.tf
https://github.com/nebius/soperator/issues/910
> Remove Grafana Auth

- .github/workflows/terraform.yml
Fix for 
```
ERROR: Parameter problem: Please use --force to delete ALL contents of s3://storagebucket-e0014758515974559378561
```
> [FIX] Add force bucket cleanup arg

- .github/workflows/terraform.yml
Patch for cleanup pipeline part to continue if error at bucket-cleanup step occur + xargs verbosity switched on
> [FIX] Add continue-on-error

- soperator/modules/slurm/main.tf
- soperator/modules/slurm/templates/helm_values/terraform_fluxcd_values.yaml.tftpl
> #773 add telemetry_enabled in vmStack

- k8s-training/tests/k8s-training-kuberay.tftest.hcl
- k8s-training/tests/main.tftest.hcl
Fix for kuberay tests + re-org vars
> [FIX] Kuberay tests fix and test variables re-org

- soperator/modules/slurm/locals.tf
- soperator/modules/slurm/templates/helm_values/terraform_fluxcd_values.yaml.tftpl
- soperator/modules/slurm/variables.tf
- Add custom init container ensuring that jail has right fs type
- Fix vmagent resources
> Rest ensure jail

- .github/workflows/terraform.yml
Feature for triggering tests in parallel for only specified list of resources
> [FEATURE] Init parallel pipeline

- .github/workflows/terraform.yml
Due to 
```
files_ignore: '
```
> [FIX] Fix ignore pattern

- .github/workflows/terraform.yml
Add json compaction, as GH actions doesn't recognize multiline JSON
> [FIX] Add json compaction

- modules/nfs-server/disks.tf
Right now you won't be able to create several soperator clusters with nfs servers in the same project
> fix several nfs servers in one project

- soperator/installations/example/main.tf
- soperator/installations/example/terraform.tfvars
- soperator/installations/example/variables.tf
- soperator/modules/k8s/k8s_ng_workers.tf
- soperator/modules/k8s/variables.tf
> add soperator supporting driverful nodes #1361

- soperator/README.md
- soperator/modules/active_checks/main.tf
- soperator/modules/active_checks/templates/all_reduce_perf_nccl_check.yaml.tftpl
- soperator/modules/active_checks/templates/create_user_check.yaml.tftpl
- soperator/modules/active_checks/templates/create_user_soperatorchecks_action.yaml.tftpl
- soperator/modules/active_checks/templates/enroot_cleanup_check.yaml.tftpl
- soperator/modules/active_checks/templates/extensive_check.sh
- soperator/modules/active_checks/templates/extensive_check.yaml.tftpl
- soperator/modules/active_checks/templates/install_package.yaml.tftpl
- soperator/modules/active_checks/templates/run_extensive_check_on_reservations.sh
- soperator/modules/active_checks/templates/run_extensive_check_on_reservations.yaml.tftpl
- soperator/modules/active_checks/templates/ssh_check.yaml.tftpl
- soperator/modules/active_checks/templates/upgrade_cuda.yaml.tftpl
- soperator/modules/active_checks/variables.tf
See the source PR for more info: https://github.com/nebius/soperator/pull/1377
Depends on PR: https://github.com/nebius/nebius-solutions-library/pull/488
This PR includes:
- Use the new version of the controller
- Use the new version of soperator helm chart which contains the CRDs
- Changes to active checks.
⚠️  Don't merge until https://github.com/nebius/nebius-solutions-library/pull/488 is meged
> slurm reservation for suspicious nodes 2

- .github/workflows/biweekly_release.yml
> Archteam-1003 - remove manual trigger

- soperator/modules/monitoring/templates/dashboards/cluster_health.json
- soperator/modules/monitoring/templates/dashboards/jobs_overview.json
> Filter out job run by soperatorchecks username from graphs 

- modules/nccl-test/main.tf
Update Helm provider syntax change in v3 for nccl-tests module
https://registry.terraform.io/providers/hashicorp/helm/latest/docs/guides/v3-upgrade-guide
> [FIX] Fix nccl-tests helm v3 terraform provided

- anyscale/.gitignore
- anyscale/README.md
- anyscale/default.yaml.tpl
- anyscale/deploy/local.tf
- anyscale/deploy/main.tf
- anyscale/deploy/provider.tf
- anyscale/deploy/variables.tf
- anyscale/environment.sh
- anyscale/prepare/local.tf
- anyscale/prepare/main.tf
- anyscale/prepare/output.tf
- anyscale/prepare/provider.tf
- anyscale/prepare/variables.tf
- anyscale/register.sh
- k8s-training/gpu_cluster.tf
- k8s-training/main.tf
- k8s-training/variables.tf
- modules/cilium-egress-gateway/main.tf
- nfs-server/output.tf
This PR makes it easy to install Anyscale operator on Nebius Cloud.
> Added Anyscale

- soperator/modules/slurm/main.tf
- soperator/modules/slurm/scripts/wait_for_flux_hr.sh.tmpl
- soperator/modules/slurm/templates/helm_values/terraform_fluxcd_values.yaml.tftpl
> Fix timeouts for wait-activechecks

- soperator/modules/slurm/templates/helm_values/terraform_fluxcd_values.yaml.tftpl
> DCGM Exporter does not need to know about drivers

- soperator/modules/slurm/templates/helm_values/terraform_fluxcd_values.yaml.tftpl
> del k8up values null

- soperator/installations/example/main.tf
- soperator/modules/slurm/main.tf
- soperator/modules/slurm/variables.tf
Fix invalid git ref for stable deployments
> fix invalid stable git ref

- gpu_slicing/README.md
- gpu_slicing/mig/README.md
- gpu_slicing/mps/README.md
- gpu_slicing/timeslice/README.md
Adds guides on how to slice a GPU with MIG, MPS and Time Slicing.
> GPU slicing guides

- anyscale/README.md
- anyscale/default.yaml.tpl
- anyscale/deploy/bucket_key.tf
- anyscale/deploy/main.tf
Create Object Storage key pair in TF instead of CLI
> create bucket keypair in tf instead of CLI

- .github/workflows/terraform.yml
Set trigger of detect-changes job to always ( on PR open )
> [FEATURE] Always trigger detect changes job in the pipeline
