nebius/nebius-solutions-library

k8s-training/README.md
- `nebius init` is no longer a valid command
- added a command to install `jq` on macos
=> [k8s-training] README updates

soperator/Makefile, soperator/installations/example/.envrc, soperator/installations/example/main.tf, soperator/installations/example/variables.tf, soperator/modules/available_resources/main.tf, soperator/modules/k8s/k8s_ng_accounting.tf, soperator/modules/k8s/k8s_ng_controller.tf, soperator/modules/k8s/k8s_ng_login.tf, soperator/modules/k8s/k8s_ng_system.tf, soperator/modules/k8s/k8s_ng_workers.tf, soperator/modules/slurm/main.tf, soperator/modules/slurm/templates/helm_values/slurm_cluster.yaml.tftpl, soperator/modules/slurm/variables.tf
- Filter service accounts with jq, as filtering via API is not implemented
- Fix for division worker nodeset into node groups
- Remove setting K8s version for node groups
- Do not access accounting resources when it's disabled
- Remove registry from version sync
- Add support for new platforms
=> Soperator deployment fixes

k8s-inference/main.tf, k8s-training/main.tf
replace `public_ip` with `public_ip_address` in `k8s-inference` and `k8s-training`
=> fix public ip allocation for gpu nodes

soperator/.gitignore, soperator/installations/example/variables.tf, soperator/modules/slurm/templates/helm_values/slurm_cluster.yaml.tftpl
Since when deploying through Terraform, the values `yes` and `no` are treated as booleans rather than strings, a workaround has been implemented to check these values and wrap them in quotes, thereby converting them into strings instead of booleans.
=> MSP-3518: add slurmdbd_config and slurm_config configurable

slurm/files/cloud-config-master.yaml.tftpl, slurm/gpu_cluster.tf
1. **Updated `infiniband_fabric` configuration in [slurm/gpu_cluster.tf](https://github.com/nebius/nebius-solution-library/compare/main...PhilipMantrov:nebius-solution-library:main?expand=1#diff-b16280cf03d591628adc225365d1d6a52d4396639d4afcb8439d36850cb6a5cd)**  
- Added eu-west1 variant `infiniband_fabric = "fabric-5"` with comment section.
**Reason:** `fabric-3` is not available in the `eu-west1` region.
2. **Added hostname to [slurm/files/cloud-config-master.yaml.tftpl](https://github.com/nebius/nebius-solution-library/compare/main...PhilipMantrov:nebius-solution-library:main?expand=1#diff-2698abb5db964a4983004a5f8de0294fafc2fc81bcb25cb47879879caab3bc6c)**  
- Added `hostname: slurm-master` to the `cloud-config-master.yaml.tftpl` file.  
**Reason:** Initialization scripts fail during …
=> fix: minimal fixes for eu-west1

.github/workflows/terraform.yml, modules/csi-mounted-fs-path/csi-driver.tf
This version allows to provide tolerations for csi-mounted-fs-path pods.
=> Update csi-mounted-fs-path to 0.1.2

soperator/modules/k8s/k8s_ng_accounting.tf, soperator/modules/k8s/k8s_ng_controller.tf, soperator/modules/k8s/k8s_ng_login.tf, soperator/modules/k8s/k8s_ng_system.tf, soperator/modules/k8s/k8s_ng_workers.tf, soperator/modules/labels/main.tf, soperator/modules/labels/outputs.tf, soperator/modules/slurm/templates/helm_values/slurm_cluster_storage.yaml.tftpl
```
% k get pv jail-submount-shared-pv -oyaml
apiVersion: v1
kind: PersistentVolume
metadata:
annotations:
meta.helm.sh/release-name: slurm-cluster-storage
meta.helm.sh/release-namespace: soperator
creationTimestamp: "2025-03-25T09:08:44Z"
finalizers:
- kubernetes.io/pv-protection
labels:
app.kubernetes.io/managed-by: Helm
name: jail-submount-shared-pv
resourceVersion: "5237"
uid: 00ad67dc-e4b9-4f50-8453-191e60559bf6
spec:
accessModes:
- ReadWriteMany
capacity:
storage: 2Ti
claimRef:
apiVersion: v1
kind: PersistentVolumeClaim
name: jail-submount-shared-pvc
namespace: soperator
resourceVersion: "5233"
uid: 31a318f4-8d2e-43f6-aac3-2ec928094204
local:
path: /mnt/jail-submount-shared
mountOptions:
- rw
- relatime
- exec
nodeAffinity:
required:
nodeSelectorTerms:
- matchExpressions:
- key: …
```
=> Soperator: Add a common label to all worker nodegroups and use it in nodeAffinity #232

skypilot/examples/basic-job.yaml, skypilot/examples/test-cloud-bucket.yaml
When the `echo` argument is a double-quote string, everything wrapped in backticks is considered a command and executed. I replace double quotes with single quotes.
=> Replace quotes in Skypilot task `echo`s

.github/workflows/terraform.yml
In `.github/workflows/terraform.yml` the tests are are run using matrix, which uses the same code, but changes up the variable in the matrix.
With the current setting of `jobs.terraform.strategy.max-parallel: 2`, two jobs can run at the same time, both check out the gh-pages branch at the `Load test report history` step and then one of them pushes updates at the `Publish test report` step.
The 2nd test running in parallel will get an error like below and fail:
```
/usr/bin/git push origin gh-pages
To https://github.com/nebius/nebius-solution-library.git
! [rejected]          gh-pages -> gh-pages (non-fast-forward)
error: failed to push some refs to 'https://github.com/nebius/nebius-solution-library.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its …
```
=> fix tests race condition by only running one at a time

k8s-training/README.md, k8s-training/helm.tf, k8s-training/locals.tf, k8s-training/main.tf, k8s-training/terraform.tfvars, k8s-training/variables.tf, modules/gpu-operator/main.tf, modules/gpu-operator/variables.tf
This PR adds 2 things:
- Setting `mig.strategy` for `gpu-operator` module
- Setting node label with MIG partitioning configuration for `k8s-training`
To use with `k8s-training`, edit the `terraform.tfvars` file:
```hcl
mig_strategy = "mixed"       # If set, possible values include 'single', 'mixed', 'none'
mig_parted_config = "all-1g.20gb" # If set, value will be checked against allowed for the selected 'gpu_nodes_platform'
```
This configuration will apply `mixed` MIG strategy to the `gpu-operator` (meaning the resulting MIG slices will appear as `nvidia.com/mig-<slice-type>` resource) and the slicing of type `all-1g.20gb` (only applicable to H100 GPU, possible values are validated with GPU platform, see [this link for MIG profile](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/# …
=> add MIG configuration to 'gpu-operator' and 'k8s-training'

soperator/installations/example/main.tf, soperator/installations/example/terraform.tfvars, soperator/installations/example/variables.tf, soperator/modules/slurm/main.tf, soperator/modules/slurm/templates/helm_values/slurm_cluster.yaml.tftpl, soperator/modules/slurm/variables.tf
Solves https://github.com/nebius/soperator/issues/641
Also removed `Nodes=worker-[0-15]` from partition configuration suggestion since it is not supported by soperator.
=> Add worker features support

modules/gluster-module/instances.tf, modules/gluster-module/variables.tf, modules/instance/main.tf, modules/instance/variables.tf, modules/nfs-server/main.tf, modules/nfs-server/variables.tf, vm-instance/README.md, vm-instance/terraform.tfvars, vm-instance/variables.tf
nfs-server
- Old behavior: create public IP for instance
- New behavior: create public IP for instance if public_ip = true
- public_ip = false by default
gluster
- Old behavior: create public IP for instance if it's the first instance created via this module.
- New behavior: create public IP for instance if it's the first instance created via this module and if public_ip = true
- public_ip = false by default
instance
- Old behavior: create public IP for instance
- New behavior: create public IP for instance if it's the first instance created via this module and if public_ip = true OR if create_public_ip_for_all_instances = true.
- public_ip = true by default
- create_public_ip_for_all_instances = false by default
=> Changed public IP behavior

soperator/modules/monitoring/templates/dashboards/jobs_overview.yaml.tftpl
We went from Prometheus stack to VictoriaMetrics stack, hence the datasource name change.
=> Fix dashboard datasource

soperator/modules/monitoring/templates/dashboards/workers_detailed_stats.yaml.tftpl
With addition of `hpc_job` label on `DCGM_` metrics, plain queries return multiple series that look like duplicate GPUs.
Aggregating without that label fixes the view.
=> Fix Worker Detailed Stats dashboard

soperator/modules/monitoring/templates/dashboards/jobs_overview.yaml.tftpl, soperator/modules/monitoring/templates/dashboards/workers_detailed_stats.yaml.tftpl
Changes make panels worker **and** node specific (new, old):
It would previously show stats from all nodes that the selected worker was scheduled on during the selected window of time.
A new row with per worker stats (similar to Workers Overview dahsboard) is added, this helps when users are looking for outliers among many workers of a job, or when variance in cluster based metrics are high.
=> Grafana dashboard fixes

k8s-training/variables.tf
Avoid hardcoding k8s version
- Setting as null resolves with Nebius' backend default Kubernetes version
- 1.30 will be deprecated end of June
=> Issue 905/fix k8s version

soperator/installations/example/terraform.tfvars, soperator/installations/example/variables.tf, soperator/modules/slurm/variables.tf
Disabling by default since introduction of ActiveChecks
=> Disable nccl benchmark by default

.github/workflows/terraform.yml
Fix for incorrect usage of bucket.id in s3cmd command switched to bucket.name.  And tests-report-bucket excluded from the cleanup
=> [FIX] Exclude test-reports bucket from the cleanup

.github/workflows/terraform.yml
Cleanup pipelines fails due to within the tenant hosted the reports bucket which is not empty and shouldn't be a part of cleanup
=> [FIX] Exclude reports bucket from cleanup

soperator/modules/slurm/locals.tf, soperator/modules/slurm/main.tf, soperator/modules/slurm/templates/helm_values/terraform_fluxcd_values.yaml.tftpl
Implements dynamic scaling of vmagent remote write queues based on cluster worker count using formula `2 + floor(sum(worker_count) / 80)`.
- Replace hardcoded `queues: 2` with dynamic calculation
- Small clusters (≤79 workers): 2 queues
- Large clusters (160+ workers): 4+ queues
This improves metrics ingestion performance for larger clusters.
=> Scale vmagent remote write queues based on worker count for better performance

k8s-training/tests/main.tftest.hcl, modules/o11y/test-resources.tf
Remove the deprecated asserts tests suits due to changes in TF state structure. 
```
terraform state list
data.nebius_iam_v1_group.editors[0]
nebius_compute_v1_filesystem.shared-filesystem[0]
nebius_compute_v1_gpu_cluster.fabric_2
nebius_iam_v1_group_membership.k8s_node_group_sa-admin[0]
nebius_iam_v1_service_account.k8s_node_group_sa[0]
nebius_mk8s_v1_cluster.k8s-cluster
nebius_mk8s_v1_node_group.cpu-only
nebius_mk8s_v1_node_group.gpu[0]
random_string.random
module.gpu-operator[0].nebius_applications_v1alpha1_k8s_release.this
module.network-operator.nebius_applications_v1alpha1_k8s_release.this
module.o11y.kubernetes_annotations.restart_grafana
module.o11y.nebius_applications_v1alpha1_k8s_release.prometheus[0]
module.o11y.random_password.grafana[0]
module.o11y.time_static.restarted_at …
```
=> [FIX] Fix for depricated and zero TF states

vm-instance/.envrc.sh, vm-instance/.envrc.zsh, vm-instance/terraform.tfvars
--- [in `vm-instance/.envrc.sh/zsh`] ---
In line 178 the `NEBIUS_REGION` is set by `nebius iam project get --id "$project_id" | awk '/region:/ {print $2}'`. This will result in setting the region to:
```
<region>
<region>
```
rather than the intended 
```
<region>
```
This happens since the output of `nebius iam project get --id "$project_id"` has `region:` twice (in `spec:` and `status:`). This is resolved by changing it to `NEBIUS_REGION=$(nebius iam project get --id "$project_id" --format json | jq -r '.spec.region')` - taking the region only from the spec
--- [in `vm-instance/.envrc.sh/zsh`] ---
Configurations for the awscli are written to `./.aws/config`. By default the awscli expects this in `~/.aws/config` so the configuration will only be found when the code is executed from the …
=> Fixed small changes 

soperator/modules/monitoring/templates/dashboards/jobs_overview.json, soperator/modules/monitoring/templates/dashboards/update-dashboards.sh, soperator/modules/monitoring/templates/dashboards/workers_detailed_stats.json, soperator/modules/monitoring/templates/dashboards/workers_overview.json
Added GPU theoretical FLOPS monitoring to soperator Grafana dashboards using DCGM tensor core activity metrics.
- **Workers Detailed Stats**: Added 3 new panels showing GPU tensor activity percentage and theoretical FLOPS for FP8 and FP16/BF16 precisions
- **Jobs Overview**: Updated GPU performance panel to display theoretical FLOPS with FP8 and FP16/BF16 lines
- **Workers Overview**: Added GPU theoretical FLOPS panel to cluster stats section
- **Update Script**: Created `update-dashboards.sh` script for easy dashboard updates across Kubernetes clusters
The FLOPS calculations use `DCGM_FI_PROF_PIPE_TENSOR_ACTIVE` metric multiplied by H100 peak performance:
- FP8: × 1979 TFLOPS
- FP16/BF16: × 989.7 TFLOPS
The update script supports:
- Context switching for different clusters
- Change …
=> Add GPU FLOPS monitoring to Grafana dashboards

.github/workflows/terraform.yml
Fir for the following error
```
[Invalid workflow file: .github/workflows/terraform.yml#L37](https://github.com/nebius/nebius-solutions-library/actions/runs/16442313238/workflow)
The workflow is not valid. .github/workflows/terraform.yml (Line: 37, Col: 11): A sequence was not expected .github/workflows/terraform.yml (Line: 45, Col: 14): Unexpected symbol: '$dedup'. Located at position 14 within expression: toJson(split($dedup, ' '))
```
=> [FIX] Fix parallel pipeline

.github/workflows/soperator.yml
This PR fixes the soperator release workflow to ensure GitHub releases are created with tags pointing to the actual commit that triggered the workflow, rather than defaulting to the main branch.
=> Fix soperator release workflow to tag correct commit instead of main

soperator/installations/example/main.tf, soperator/installations/example/terraform.tfvars, soperator/installations/example/variables.tf, soperator/modules/available_resources/preset.tf, soperator/modules/k8s/variables.tf, soperator/modules/slurm/main.tf, soperator/modules/slurm/templates/helm_values/terraform_fluxcd_values.yaml.tftpl, soperator/modules/slurm/variables.tf
- Allocate only half of the total memory in jobs by default
- Forbid creating clusters without jail submounts by default
- Deprecate the use of filestore for storing controller state
- Add min sizes for K8s node boot disks
- Make Slurm accounting required
=> Forbid clusters without jail submounts and other changes

soperator/modules/active_checks/templates/soperator_outputs_logs_cleaner.tftpl
`wait-for-checks` will keep waiting forever because logs-cleaner doesn't run after creation. This PR changes it to `runAfterCreation: true`
=> logs-cleaner runAfterCreation: true

soperator/modules/active_checks/templates/soperator_outputs_logs_cleaner.tftpl
Merge back PR
https://github.com/nebius/nebius-solutions-library/pull/497
`wait-for-checks` will keep waiting forever because logs-cleaner doesn't run after creation. This PR changes it to `runAfterCreation: true`
=> [Merge to main] logs-cleaner runAfterCreation: true

soperator/modules/slurm/templates/helm_values/terraform_fluxcd_values.yaml.tftpl
Otherwise, default value for `ENROOT_DATA_PATH` is used
=> Overwrite Enroot's custom dirs if image disks are used

soperator/modules/slurm/templates/helm_values/terraform_fluxcd_values.yaml.tftpl
Cherry-picked from #547
Otherwise, default value for `ENROOT_DATA_PATH` is used
=> [cherry-pick] Overwrite Enroot's custom dirs if image disks are used

soperator/installations/example/.envrc
Added `AWS_REGION` and `AWS_ENDPOINT_URL` to cleanup backup buckets on destroy in different regions
=> add more aws variables for proper cleanup

soperator/modules/cleanup/scripts/disk_cleanup.sh
Add `nfs-system` to the allowed namespaces, so any disk that has label `kubernetes.io/created-for/pvc/namespace: nfs-system` and is not attached to any instance will be deleted during the `terraform destroy`
=> add nfs-system to the allowed namespaces for cleanup

.github/workflows/soperator.yml
Change to manual triggering, so when we test 1.22.0, it will no longer be called 1.21.14: we can rename it first, and then make a release.
Same was already done in soperator itself: https://github.com/nebius/soperator/pull/1609/files
=> Change soperator release workflow to manual triggering only
